// API Configuration
const API_URL = 'http://127.0.0.1:8000/career-copilot';

// DOM Elements
const submitBtn = document.getElementById('submitBtn');
const btnText = document.getElementById('btnText');
const errorAlert = document.getElementById('errorAlert');
const errorMessage = document.getElementById('errorMessage');
const resultSection = document.getElementById('resultSection');
const resultText = document.getElementById('resultText');
const generatedBy = document.getElementById('generatedBy');

// Form Fields
const branchInput = document.getElementById('branch');
const yearInput = document.getElementById('year');
const skillsInput = document.getElementById('skills');
const interestsInput = document.getElementById('interests');
const strengthsInput = document.getElementById('strengths');
const weaknessesInput = document.getElementById('weaknesses');

// Get form data
function getFormData() {
    return {
        branch: branchInput.value.trim(),
        year: parseInt(yearInput.value),
        skills: skillsInput.value.trim(),
        interests: interestsInput.value.trim(),
        strengths: strengthsInput.value.trim(),
        weaknesses: weaknessesInput.value.trim()
    };
}

// Validate form
function validateForm() {
    const data = getFormData();
    
    if (!data.branch || !data.year || !data.skills || !data.interests || !data.strengths || !data.weaknesses) {
        return 'Please fill in all fields';
    }
    
    if (isNaN(data.year) || data.year < 1 || data.year > 5) {
        return 'Please enter a valid year (1-5)';
    }
    
    return null;
}

// Show error
function showError(message) {
    errorMessage.textContent = message;
    errorAlert.style.display = 'flex';
    resultSection.style.display = 'none';
}

// Hide error
function hideError() {
    errorAlert.style.display = 'none';
}

// Show result
function showResult(data) {
    hideError();
    generatedBy.textContent = `Generated by ${data.generated_by}`;
    resultText.textContent = data.career_guidance;
    resultSection.style.display = 'block';
    
    // Smooth scroll to result
    resultSection.scrollIntoView({ behavior: 'smooth', block: 'nearest' });
}

// Set loading state
function setLoading(isLoading) {
    submitBtn.disabled = isLoading;
    
    if (isLoading) {
        submitBtn.classList.add('loading');
        btnText.textContent = 'Generating Guidance...';
        // Change icon to loading spinner
        const icon = submitBtn.querySelector('.btn-icon');
        icon.innerHTML = '<circle cx="12" cy="12" r="10" stroke="currentColor" stroke-width="2" fill="none"></circle>';
    } else {
        submitBtn.classList.remove('loading');
        btnText.textContent = 'Generate Career Guidance';
        // Restore original icon
        const icon = submitBtn.querySelector('.btn-icon');
        icon.innerHTML = '<path d="M12 2l3.09 6.26L22 9.27l-5 4.87 1.18 6.88L12 17.77l-6.18 3.25L7 14.14 2 9.27l6.91-1.01L12 2z"/>';
    }
}

// Main submit handler
async function handleSubmit() {
    // Validate form
    const validationError = validateForm();
    if (validationError) {
        showError(validationError);
        return;
    }
    
    // Hide previous results/errors
    hideError();
    resultSection.style.display = 'none';
    
    // Set loading state
    setLoading(true);
    
    try {
        const formData = getFormData();
        
        // Make API request
        const response = await fetch(API_URL, {
            method: 'POST',
            headers: {
                'Content-Type': 'application/json',
            },
            body: JSON.stringify(formData)
        });
        
        // Check if response is OK
        if (!response.ok) {
            throw new Error(`API request failed with status ${response.status}`);
        }
        
        // Parse response
        const data = await response.json();
        
        // Check for success status
        if (data.status !== 'success') {
            throw new Error('API returned an error status');
        }
        
        // Show result
        showResult(data);
        
    } catch (error) {
        console.error('Error:', error);
        
        // Show user-friendly error message
        let errorMsg = 'Failed to generate career guidance. ';
        
        if (error.message.includes('Failed to fetch') || error.message.includes('NetworkError')) {
            errorMsg += 'Please make sure the backend server is running at ' + API_URL;
        } else if (error.message.includes('status')) {
            errorMsg += 'The server returned an error. Please try again.';
        } else {
            errorMsg += 'Please check your connection and try again.';
        }
        
        showError(errorMsg);
    } finally {
        // Reset loading state
        setLoading(false);
    }
}

// Handle Enter key in text inputs (not textareas)
branchInput.addEventListener('keypress', (e) => {
    if (e.key === 'Enter') {
        e.preventDefault();
        handleSubmit();
    }
});

yearInput.addEventListener('keypress', (e) => {
    if (e.key === 'Enter') {
        e.preventDefault();
        handleSubmit();
    }
});

// Clear error when user starts typing
[branchInput, yearInput, skillsInput, interestsInput, strengthsInput, weaknessesInput].forEach(input => {
    input.addEventListener('input', hideError);
});